name: Deploy Laravel Project on push
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gpacalculator  # Set the working directory at the job level

    steps:
      - name: Get the latest code
        uses: actions/checkout@v4.0.0

      - uses: actions/setup-node@v2  # Use the latest version of setup-node action

      - name: Install Dependencies
        run: composer update -n --prefer-dist

      - name: Setup Project
        run: php artisan optimize:clear

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /gpacalculator.alphaflare.co.ke/
          debug: true
